default_stages:
  - "pre-commit"
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: ruff
        name: Format with Ruff
        entry: make fmt
        language: system
        types: [python]
        pass_filenames: false

      - id: pyright
        name: Validate types with pyright
        entry: make pyright
        language: system
        types: [python]
        pass_filenames: false
