[tool.poetry]
name = "orbitcloud-graviton"
version = "0.15.0"
description = ""
authors = ["Orbit Team <admin@orbit.is>"]
license = "MIT"
readme = "README.md"
packages = [
    # Lib and helpers
    { include = "orbitcloud_graviton/pulumi_mocks", from = "components" },
    { include = "orbitcloud_graviton/az_lib", from = "components" },

    # Azure Components
    { include = "orbitcloud_graviton/az_acr", from = "components" },
    { include = "orbitcloud_graviton/az_appservice", from = "components" },
    { include = "orbitcloud_graviton/az_keyvault", from = "components" },
    { include = "orbitcloud_graviton/az_monitor", from = "components" },
    { include = "orbitcloud_graviton/az_resources", from = "components" },

    # Bases
    { include = "orbitcloud_graviton/appservice_suite", from = "bases" },
    { include = "orbitcloud_graviton/landing_site", from = "bases" },
]

[tool.poetry.dependencies]
python = "^3.10"
pulumi = "^3.81"
pulumi-azure-native = "^2.11"
beartype = "^0.16.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
commitizen = "^3.7.0"
pytest-xdist = "^3.3.1"
pyright = "^1.1.327"
pylint = "^3.0.1"
pre-commit = "^3.4.0"
black = "^23.9.1"
flake8 = "^6.1.0"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.15.0"
tag_format = "v$version"
version_files = [
    "VERSION",
    "pyproject.toml:^version",
    ]
update_changelog_on_bump = true
changelog_incremental = true
bump_message = "bump: $current_version → $new_version"
major_version_zero = true # Remove when we hit 1.0.0

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
