[tool.poetry]
name = "orbitcloud-graviton"
version = "0.16.0"
description = ""
authors = ["Orbit Team <admin@orbit.is>"]
license = "MIT"
readme = "README.md"
packages = [
    # Lib and helpers
    { include = "orbitcloud_graviton/pulumi_mocks", from = "components" },
    { include = "orbitcloud_graviton/az_lib", from = "components" },
    # Azure Components
    { include = "orbitcloud_graviton/az_acr", from = "components" },
    { include = "orbitcloud_graviton/az_app", from = "components" },
    { include = "orbitcloud_graviton/az_appservice", from = "components" },
    { include = "orbitcloud_graviton/az_keyvault", from = "components" },
    { include = "orbitcloud_graviton/az_monitor", from = "components" },
    { include = "orbitcloud_graviton/az_resources", from = "components" },
    {include = "orbitcloud_graviton/az_storage",from = "components"},
    {include = "orbitcloud_graviton/az_iam",from = "components"},
    {include = "orbitcloud_graviton/az_network",from = "components"},
    {include = "orbitcloud_graviton/entra_app",from = "components"},
    {include = "orbitcloud_graviton/pulumi_lib",from = "components"},
    # Bases
    { include = "orbitcloud_graviton/appservice_suite", from = "bases" },
    {include = "orbitcloud_graviton/landing_zone",from = "bases"},
    {include = "orbitcloud_graviton/landing_site",from = "bases"},
    {include = "orbitcloud_graviton/network",from = "bases"},
]

[tool.poetry.dependencies]
python = "^3.11"
pulumi = "^3.102"
pulumi-azure-native = "^2.26"
beartype = "^0.16.4"
pulumi-azuread = "^5.47.0"
pydantic = "^2.5.3"
pydantic-settings = "^2.1.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-cov = "^4.1.0"
commitizen = "^3.13.0"
pytest-xdist = "^3.5.0"
pyright = "^1.1.348"
pre-commit = "^3.6.0"
debugpy = "^1.8.0"
ruff = "^0.1.14"

[tool.pyright]
include = ["components", "bases", "development", "test"]
ignore = ["test/*", "development/*", "**/__pycache__/*", "**/*.pyc"]
extraPaths = ["components", "bases"]
venvPath = ".venv"

[tool.ruff]
line-length = 120
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP", # pyupgrade
    "I",  # isort
]
ignore = [
    "E501", # line too long, handled by black
    "B008", # do not perform function calls in argument defaults
    "C901", # too complex
    "W191", # indentation contains tabs
]
extend-exclude = [
    # "development/*",
    "tests/*",
]

[tool.ruff.lint.isort]
known-third-party = ["pulumi_azure_native", "pulumi_azuread", "pulumi"]
known-first-party = ["orbitcloud_graviton"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.16.0"
tag_format = "v$version"
version_files = [
    "VERSION",
    "pyproject.toml:^version",
    ]
update_changelog_on_bump = true
changelog_incremental = true
bump_message = "bump: $current_version → $new_version"
major_version_zero = true # Remove when we hit 1.0.0

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
