[tool.poetry]
name = "orbitcloud-graviton"
version = "0.1.0"
description = ""
authors = ["Orbit Team <admin@orbit.is>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "orbitcloud_graviton/azure_helpers", from = "components" },
    { include = "orbitcloud_graviton/azure_loganalytics_workspace", from = "components" },
    { include = "orbitcloud_graviton/azure_resource_group", from = "components" },
]

[tool.poetry.dependencies]
python = "^3.11"
pulumi = "^3.79.0"
pulumi-azure-native = "^2.4.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
mypy = "^1.5.1"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
