from typing import Any

LOCATION_ABBR: dict[str, str] = {
    "westeurope": "weu",
    "northeurope": "neu",
    "norwayeast": "noe",
    "norwaywest": "now",
    "swedencentral": "swe",
}

RESOURCE_PREFIXES: dict[str, Any] = {
    "pulumi_azure_native.resources.resource_group": {"prefix": "rg"},
    "pulumi_azure_native.operationalinsights.workspace": {
        "prefix": "log",
    },
    "pulumi_azure_native.containerregistry.registry": {
        "prefix": "cr",
        "alphanumeric": True,
    },
    "pulumi_azure_native.monitor.diagnostic_setting": {
        "prefix": "diag",
    },
    "pulumi_azure_native.web.app_service_plan": {
        "prefix": "asp",
    },
    "pulumi_azure_native.web.app_service": {
        "prefix": "app",
    },
    "pulumi_azure_native.keyvault.vault": {
        "prefix": "kv",
        "alphanumeric": True,
        "max_length": 24,
    },
    "pulumi_azure_native.storage.storage_account": {
        "prefix": "st",
        "alphanumeric": True,
        "lowercase": True,
    },
    "pulumi_azure_native.network.private_dns_zone_group": {
        "prefix": "pdzg",
    },
    "pulumi_azure_native.app.managed_environment": {
        "prefix": "cae",
        "max_length": 60,
    },
    "pulumi_azure_native.network.virtual_network": {
        "prefix": "vnet",
    },
    "pulumi_azure_native.network.subnet": {
        "prefix": "snet",
    },
    "pulumi_azure_native.network.virtual_wan": {
        "prefix": "vwan",
    },
    "pulumi_azure_native.network.virtual_hub": {
        "prefix": "vhub",
    },
    "pulumi_azure_native.network.vpn_server_configuration": {
        "prefix": "vpnconf",
    },
    "pulumi_azure_native.network.p2s_vpn_gateway": {
        "prefix": "vpng",
    },
    "pulumi_azure_native.network.hub_virtual_network_connection": {
        "prefix": "vhubc",
    },
    "pulumi_azure_native.eventhub.namespace": {"prefix": "evhns"},
    "pulumi_azure_native.eventhub.event_hub": {"prefix": "evh"},
    "pulumi_azure_native.eventhub.namespace_authorization_rule": {"prefix": "evhns-key"},
    "pulumi_azure_native.eventhub.namespace_network_rule_set": {"prefix": "evhns-nwrule"},
    "pulumi_azure_native.storage.table": {"prefix": "sttbl"},
    "pulumi_azure_native.storage.blob_container": {"prefix": "stctr"},
    "pulumi_azure_native.storage.queue": {"prefix": "stq"},
    "pulumi_azure_native.storage.file_share": {"prefix": "stfs"},
    "pulumi_azure_native.storage.file_service_properties": {"prefix": "stfsp"},
    "pulumi_azure_native.providerhub.provider_registration": {"prefix": "proreg"},
    "pulumi_azure_native.providerhub.resource_type_registration": {"prefix": "prov"},
    "pulumi_azure_native.keyvault.secret": {"prefix": "kvs"},
    "pulumi_azure_native.app.container_app": {"prefix": "app"},
    "pulumi_azure_native.app.managed_certificate": {"prefix": "cert"},
    "pulumi_azure_native.app.certificate": {"prefix": "caecert-"},
    "pulumi_azure_native.app.app_resiliency": {"prefix": "appres"},
    "pulumi_azure_native.applicationinsights.component": {"prefix": "appi"},
    "pulumi_azure_native.dns.zone": {"prefix": "dns"},
    "pulumi_azure_native.dns.record_set": {"prefix": "dnsr"},
    "pulumi_azure_native.privatedns.private_record_set": {"prefix": "dnsr"},
    "pulumi_azure_native.network.vpn_gateway": {"prefix": "vpng"},
    "pulumi_azure_native.network.virtual_network_gateway": {"prefix": "vgw"},
    "pulumi_azure_native.network.virtual_network_gateway_connection": {"prefix": "con"},
    "pulumi_azure_native.network.local_network_gateway": {"prefix": "lgw"},
    "pulumi_azure_native.dnsresolver.dns_resolver": {"prefix": "dnspr"},
    "pulumi_azure_native.dnsresolver.inbound_endpoint": {"prefix": "in"},
    "pulumi_azure_native.dnsresolver.outbound_endpoint": {"prefix": "out"},
    "pulumi_azure_native.dnsresolver.dns_forwarding_ruleset": {"prefix": "dnsfrs"},
    "pulumi_azure_native.authorization.role_assignment": {"prefix": "iam"},
    "pulumi_azure_native.managedidentity.user_assigned_identity": {"prefix": "id"},
    "pulumi_azure_native.appconfiguration.configuration_store": {"prefix": "appcs"},
    "pulumi_azure_native.appconfiguration.key_value": {"prefix": "appcsk"},
    "pulumi_azure_native.eventgrid.domain": {"prefix": "evgd"},
    "pulumi_azure_native.eventgrid.domain_topic": {"prefix": "evgt"},
    "pulumi_azure_native.network.private_endpoint": {"prefix": "pep"},
    "pulumi_azure_native.search.service": {"prefix": "srch"},
    "pulumi_azure_native.cognitiveservices.account": {"prefix": "oai"},
    "pulumi_azure_native.dbforpostgresql.server": {"prefix": "psql"},
    "pulumi_azure_native.dbforpostgresql.administrator": {"prefix": "psql-admin"},
    "pulumi_azure_native.dbforpostgresql.configuration": {"prefix": "psql-conf"},
    "pulumi_azure_native.servicebus.namespace": {"prefix": "sbns"},
    "pulumi_azure_native.servicebus.queue": {"prefix": "sbq"},
    "pulumi_azure_native.servicebus.topic": {"prefix": "sbt"},
    "pulumi_azure_native.servicebus.namespace_network_rule_set": {"prefix": "sbns-nwrule"},
    "pulumi_azure_native.servicebus.namespace_ip_filter_rule": {"prefix": "sbns-iprule"},
    "pulumi_azure_native.sql.database": {"prefix": "sqldb"},
    "pulumi_azure_native.sql.server": {"prefix": "sql"},
    "pulumi_azure_native.sql.elastic_pool": {"prefix": "sqlep"},
    "pulumi_azure_native.sql.firewall_rule": {"prefix": "sqlfw"},
    "pulumi_azure_native.sql.server_dns_alias": {"prefix": "sqldns"},
    "pulumi_azure_native.sql.job_agent": {"prefix": "sqlja"},
    "pulumi_azure_native.sql.job_target_group": {"prefix": "sqljtg"},
    "pulumi_azure_native.sql.job": {"prefix": "sqljob"},
    "pulumi_azure_native.sql.job_step": {"prefix": "sqljs"},
    "pulumi_random.random_password": {"prefix": "rand"},
    "pulumi_azure_native.compute.virtual_machine": {"prefix": "vm"},
    "pulumi_azure_native.compute.disk": {"prefix": "disk"},
    "pulumi_azure_native.network.network_interface": {"prefix": "nic"},
    "pulumi_azure_native.network.azure_firewall": {"prefix": "azfw"},
    "pulumi_azure_native.network.firewall_policy": {"prefix": "azfwp"},
    "pulumi_azure_native.network.dnssec_config": {"prefix": "dnssec"},
    "pulumi_azure_native.recoveryservices.vault": {"prefix": "rsv"},
    "pulumi_azure_native.recoveryservices.protection_policy": {"prefix": "rsvpp"},
    # See Cloud Adoption Framework Abbreviations:
    # https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations
}
